apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin
  namespace: argocd
spec:
  destination:
    namespace: apps
    server: https://kubernetes.default.svc
  project: apps
  source:
    path: charts/stdapp
    repoURL: https://github.com/brunoluiz/argocd-lab
    helm:
      valueFiles:
        - values.yaml

      valuesObject:
        name: hello-world-api
        version: 0.0.0
        image:
          repository: brunoluiz/go-lab/services/hello-world/api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
