apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin
  namespace: argocd
spec:
  destination:
    namespace: apps
    server: https://kubernetes.default.svc
  project: apps
  source:
    path: charts/stdapp
    repoURL: https://github.com/brunoluiz/argocd-lab
    helm:
      valueFiles:
        - values.yaml

      valuesObject:
        name: httpbin
        version: 0.0.0
        image:
          registry: docker.io
          repository: kennethreitz/httpbin
          tag: latest
        deployment:
          ports:
            - 80
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
