// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repo

import (
	"context"
)

type Querier interface {
	DeleteList(ctx context.Context, uniqID string) error
	DeleteTask(ctx context.Context, uniqID string) error
	GetListByID(ctx context.Context, uniqID string) (List, error)
	GetLists(ctx context.Context) (List, error)
	GetTaskByID(ctx context.Context, uniqID string) (Task, error)
	GetTasks(ctx context.Context) ([]Task, error)
	SaveList(ctx context.Context, arg SaveListParams) (List, error)
	SaveTask(ctx context.Context, arg SaveTaskParams) (Task, error)
}

var _ Querier = (*Queries)(nil)
