// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: radars.sql

package repo

import (
	"context"
)

const deleteRadar = `-- name: DeleteRadar :exec
DELETE FROM radars
WHERE uniq_id = $1
`

func (q *Queries) DeleteRadar(ctx context.Context, uniqID string) error {
	_, err := q.db.ExecContext(ctx, deleteRadar, uniqID)
	return err
}

const getRadarByID = `-- name: GetRadarByID :one
SELECT id, uniq_id, title, updated_at, created_at FROM radars
WHERE uniq_id = $1 LIMIT 1
`

func (q *Queries) GetRadarByID(ctx context.Context, uniqID string) (Radar, error) {
	row := q.db.QueryRowContext(ctx, getRadarByID, uniqID)
	var i Radar
	err := row.Scan(
		&i.ID,
		&i.UniqID,
		&i.Title,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRadars = `-- name: GetRadars :many
SELECT id, uniq_id, title, updated_at, created_at FROM radars
`

func (q *Queries) GetRadars(ctx context.Context) ([]Radar, error) {
	rows, err := q.db.QueryContext(ctx, getRadars)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Radar
	for rows.Next() {
		var i Radar
		if err := rows.Scan(
			&i.ID,
			&i.UniqID,
			&i.Title,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveRadar = `-- name: SaveRadar :one
INSERT INTO radars (
  uniq_id,
  title
) VALUES ($1, $2)
ON CONFLICT (uniq_id) DO UPDATE
SET
  title = EXCLUDED.title
RETURNING id, uniq_id, title, updated_at, created_at
`

type SaveRadarParams struct {
	UniqID string `json:"uniq_id"`
	Title  string `json:"title"`
}

func (q *Queries) SaveRadar(ctx context.Context, arg SaveRadarParams) (Radar, error) {
	row := q.db.QueryRowContext(ctx, saveRadar, arg.UniqID, arg.Title)
	var i Radar
	err := row.Scan(
		&i.ID,
		&i.UniqID,
		&i.Title,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
