// Code generated by BobGen sql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Lists = Table[
	listColumns,
	listIndexes,
	listForeignKeys,
	listUniques,
	listChecks,
]{
	Schema: "",
	Name:   "lists",
	Columns: listColumns{
		ID: column{
			Name:      "id",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: listIndexes{
		ListsPkey: index{
			Type: "btree",
			Name: "lists_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "lists_pkey",
		Columns: []string{"id"},
		Comment: "",
	},

	Comment: "",
}

type listColumns struct {
	ID        column
	Name      column
	CreatedAt column
}

func (c listColumns) AsSlice() []column {
	return []column{
		c.ID, c.Name, c.CreatedAt,
	}
}

type listIndexes struct {
	ListsPkey index
}

func (i listIndexes) AsSlice() []index {
	return []index{
		i.ListsPkey,
	}
}

type listForeignKeys struct{}

func (f listForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type listUniques struct{}

func (u listUniques) AsSlice() []constraint {
	return []constraint{}
}

type listChecks struct{}

func (c listChecks) AsSlice() []check {
	return []check{}
}
