builds:
- id: brunoluiz/go-lab/services/radars/api
  main: ./services/radars/cmd/api
- id: brunoluiz/go-lab/services/hello-world
  main: ./services/hello-world/cmd/api
defaultPlatforms:
- darwin/amd64
- linux/amd64
