[tools]
air = "1.63.0"
cosign = "v2.6.1"
docker-cli = "28.4.0"
go = "1.25.2"
golangci-lint = "2.5"
ko = "0.18.0"
lefthook = "1.13.6"
trivy = "0.67.0"
prettier = "3.2.5"
"github:brunoluiz/monogo" = "v1.7.0"
buf = "1.58.0"
gomigrate = "4.19.0"
