resources:
  - ../../base

images:
  - name: image
    newName: ghcr.io/brunoluiz/go-lab/services/todo/connectrpc
    newTag: fc2574986bf76ba7776175ef0dfbc09c76c8c3d7

patches:
  - path: config.json
    target:
      group: apps
      version: v1
      kind: Deployment
      name: app
