resources:
  - ../../base

images:
  - name: image
    newName: ghcr.io/brunoluiz/go-lab/services/todo/connectrpc
    newTag: 3857739da9e27f122d6bf9b5d0ac6be544d80d85

patches:
  - path: config.json
    target:
      group: apps
      version: v1
      kind: Deployment
      name: app
