apiVersion: batch/v1
kind: CronJob
metadata:
  name: app
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid # Do not allow concurrent runs
  successfulJobsHistoryLimit: 3 # Keep last 3 successful jobs
  failedJobsHistoryLimit: 1 # Keep last 1 failed job
  startingDeadlineSeconds: 60 # If job misses schedule by 60 seconds, don't start
  jobTemplate:
    spec:
      activeDeadlineSeconds: 600 # Example: Job will be terminated after 10 minutes
      ttlSecondsAfterFinished: 3600 # Example: Job will be cleaned up 1 hour after completion
      template:
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          serviceAccountName: default
          automountServiceAccountToken: false
          containers:
            - name: app
              image: image
              imagePullPolicy: IfNotPresent
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 200m
                  memory: 256Mi
          restartPolicy: OnFailure
