services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Jaeger UI

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./testdata/devenv/otel.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP/gRPC
      - "4318:4318" # OTLP HTTP
    depends_on:
      - jaeger
