apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: hello-world
  name: api-app
spec:
  ports:
  - port: 3000
    protocol: HTTP
    targetPort: 3000
  - port: 4000
    protocol: TCP
    targetPort: 400
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: hello-world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: hello-world
  name: api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/part-of: hello-world
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/part-of: hello-world
    spec:
      automountServiceAccountToken: false
      containers:
      - image: ghcr.io/brunoluiz/go-lab/services/hello-world/api:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 10
        name: app
        ports:
        - containerPort: 3000
        - containerPort: 4000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: hello-world
  name: api-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/part-of: hello-world
