// Code generated by BobGen sql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// List is an object representing the database table.
type List struct {
	ID        string    `db:"id,pk" `
	Name      string    `db:"name" `
	CreatedAt time.Time `db:"created_at" `

	R listR `db:"-" `
}

// ListSlice is an alias for a slice of pointers to List.
// This should almost always be used instead of []*List.
type ListSlice []*List

// Lists contains methods to work with the lists table
var Lists = psql.NewTablex[*List, ListSlice, *ListSetter]("", "lists", buildListColumns("lists"))

// ListsQuery is a query on the lists table
type ListsQuery = *psql.ViewQuery[*List, ListSlice]

// listR is where relationships are stored.
type listR struct {
	Tasks TaskSlice // tasks.tasks_list_id_fkey
}

func buildListColumns(alias string) listColumns {
	return listColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "name", "created_at",
		).WithParent("lists"),
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		Name:       psql.Quote(alias, "name"),
		CreatedAt:  psql.Quote(alias, "created_at"),
	}
}

type listColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	Name       psql.Expression
	CreatedAt  psql.Expression
}

func (c listColumns) Alias() string {
	return c.tableAlias
}

func (listColumns) AliasedAs(alias string) listColumns {
	return buildListColumns(alias)
}

// ListSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ListSetter struct {
	ID        omit.Val[string]    `db:"id,pk" `
	Name      omit.Val[string]    `db:"name" `
	CreatedAt omit.Val[time.Time] `db:"created_at" `
}

func (s ListSetter) SetColumns() []string {
	vals := make([]string, 0, 3)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	return vals
}

func (s ListSetter) Overwrite(t *List) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
}

func (s *ListSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Lists.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 3)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[1] = psql.Arg(s.Name.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[2] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s ListSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ListSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 3)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	return exprs
}

// FindList retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindList(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*List, error) {
	if len(cols) == 0 {
		return Lists.Query(
			sm.Where(Lists.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Lists.Query(
		sm.Where(Lists.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Lists.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ListExists checks the presence of a single record by primary key
func ListExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return Lists.Query(
		sm.Where(Lists.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after List is retrieved from the database
func (o *List) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Lists.AfterSelectHooks.RunHooks(ctx, exec, ListSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Lists.AfterInsertHooks.RunHooks(ctx, exec, ListSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Lists.AfterUpdateHooks.RunHooks(ctx, exec, ListSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Lists.AfterDeleteHooks.RunHooks(ctx, exec, ListSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the List
func (o *List) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *List) pkEQ() dialect.Expression {
	return psql.Quote("lists", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the List
func (o *List) Update(ctx context.Context, exec bob.Executor, s *ListSetter) error {
	v, err := Lists.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single List record with an executor
func (o *List) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Lists.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the List using the executor
func (o *List) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Lists.Query(
		sm.Where(Lists.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after ListSlice is retrieved from the database
func (o ListSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Lists.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Lists.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Lists.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Lists.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o ListSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("lists", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ListSlice) copyMatchingRows(from ...*List) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ListSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Lists.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *List:
				o.copyMatchingRows(retrieved)
			case []*List:
				o.copyMatchingRows(retrieved...)
			case ListSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a List or a slice of List
				// then run the AfterUpdateHooks on the slice
				_, err = Lists.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ListSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Lists.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *List:
				o.copyMatchingRows(retrieved)
			case []*List:
				o.copyMatchingRows(retrieved...)
			case ListSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a List or a slice of List
				// then run the AfterDeleteHooks on the slice
				_, err = Lists.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ListSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ListSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Lists.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ListSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Lists.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ListSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Lists.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Tasks starts a query for related objects on tasks
func (o *List) Tasks(mods ...bob.Mod[*dialect.SelectQuery]) TasksQuery {
	return Tasks.Query(append(mods,
		sm.Where(Tasks.Columns.ListID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os ListSlice) Tasks(mods ...bob.Mod[*dialect.SelectQuery]) TasksQuery {
	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "text[]")),
	))

	return Tasks.Query(append(mods,
		sm.Where(psql.Group(Tasks.Columns.ListID).OP("IN", PKArgExpr)),
	)...)
}

func insertListTasks0(ctx context.Context, exec bob.Executor, tasks1 []*TaskSetter, list0 *List) (TaskSlice, error) {
	for i := range tasks1 {
		tasks1[i].ListID = omit.From(list0.ID)
	}

	ret, err := Tasks.Insert(bob.ToMods(tasks1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertListTasks0: %w", err)
	}

	return ret, nil
}

func attachListTasks0(ctx context.Context, exec bob.Executor, count int, tasks1 TaskSlice, list0 *List) (TaskSlice, error) {
	setter := &TaskSetter{
		ListID: omit.From(list0.ID),
	}

	err := tasks1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachListTasks0: %w", err)
	}

	return tasks1, nil
}

func (list0 *List) InsertTasks(ctx context.Context, exec bob.Executor, related ...*TaskSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	tasks1, err := insertListTasks0(ctx, exec, related, list0)
	if err != nil {
		return err
	}

	list0.R.Tasks = append(list0.R.Tasks, tasks1...)

	for _, rel := range tasks1 {
		rel.R.List = list0
	}
	return nil
}

func (list0 *List) AttachTasks(ctx context.Context, exec bob.Executor, related ...*Task) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	tasks1 := TaskSlice(related)

	_, err = attachListTasks0(ctx, exec, len(related), tasks1, list0)
	if err != nil {
		return err
	}

	list0.R.Tasks = append(list0.R.Tasks, tasks1...)

	for _, rel := range related {
		rel.R.List = list0
	}

	return nil
}

type listWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, string]
	Name      psql.WhereMod[Q, string]
	CreatedAt psql.WhereMod[Q, time.Time]
}

func (listWhere[Q]) AliasedAs(alias string) listWhere[Q] {
	return buildListWhere[Q](buildListColumns(alias))
}

func buildListWhere[Q psql.Filterable](cols listColumns) listWhere[Q] {
	return listWhere[Q]{
		ID:        psql.Where[Q, string](cols.ID),
		Name:      psql.Where[Q, string](cols.Name),
		CreatedAt: psql.Where[Q, time.Time](cols.CreatedAt),
	}
}

func (o *List) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Tasks":
		rels, ok := retrieved.(TaskSlice)
		if !ok {
			return fmt.Errorf("list cannot load %T as %q", retrieved, name)
		}

		o.R.Tasks = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.List = o
			}
		}
		return nil
	default:
		return fmt.Errorf("list has no relationship %q", name)
	}
}

type listPreloader struct{}

func buildListPreloader() listPreloader {
	return listPreloader{}
}

type listThenLoader[Q orm.Loadable] struct {
	Tasks func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildListThenLoader[Q orm.Loadable]() listThenLoader[Q] {
	type TasksLoadInterface interface {
		LoadTasks(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return listThenLoader[Q]{
		Tasks: thenLoadBuilder[Q](
			"Tasks",
			func(ctx context.Context, exec bob.Executor, retrieved TasksLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadTasks(ctx, exec, mods...)
			},
		),
	}
}

// LoadTasks loads the list's Tasks into the .R struct
func (o *List) LoadTasks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Tasks = nil

	related, err := o.Tasks(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.List = o
	}

	o.R.Tasks = related
	return nil
}

// LoadTasks loads the list's Tasks into the .R struct
func (os ListSlice) LoadTasks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	tasks, err := os.Tasks(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Tasks = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range tasks {

			if !(o.ID == rel.ListID) {
				continue
			}

			rel.R.List = o

			o.R.Tasks = append(o.R.Tasks, rel)
		}
	}

	return nil
}

type listJoins[Q dialect.Joinable] struct {
	typ   string
	Tasks modAs[Q, taskColumns]
}

func (j listJoins[Q]) aliasedAs(alias string) listJoins[Q] {
	return buildListJoins[Q](buildListColumns(alias), j.typ)
}

func buildListJoins[Q dialect.Joinable](cols listColumns, typ string) listJoins[Q] {
	return listJoins[Q]{
		typ: typ,
		Tasks: modAs[Q, taskColumns]{
			c: Tasks.Columns,
			f: func(to taskColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Tasks.Name().As(to.Alias())).On(
						to.ListID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
