// Code generated by BobGen sql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
)

// Task is an object representing the database table.
type Task struct {
	ID          string    `db:"id,pk" `
	Title       string    `db:"title" `
	IsCompleted bool      `db:"is_completed" `
	CreatedAt   time.Time `db:"created_at" `
}

// TaskSlice is an alias for a slice of pointers to Task.
// This should almost always be used instead of []*Task.
type TaskSlice []*Task

// Tasks contains methods to work with the tasks table
var Tasks = psql.NewTablex[*Task, TaskSlice, *TaskSetter]("", "tasks", buildTaskColumns("tasks"))

// TasksQuery is a query on the tasks table
type TasksQuery = *psql.ViewQuery[*Task, TaskSlice]

func buildTaskColumns(alias string) taskColumns {
	return taskColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "title", "is_completed", "created_at",
		).WithParent("tasks"),
		tableAlias:  alias,
		ID:          psql.Quote(alias, "id"),
		Title:       psql.Quote(alias, "title"),
		IsCompleted: psql.Quote(alias, "is_completed"),
		CreatedAt:   psql.Quote(alias, "created_at"),
	}
}

type taskColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ID          psql.Expression
	Title       psql.Expression
	IsCompleted psql.Expression
	CreatedAt   psql.Expression
}

func (c taskColumns) Alias() string {
	return c.tableAlias
}

func (taskColumns) AliasedAs(alias string) taskColumns {
	return buildTaskColumns(alias)
}

// TaskSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type TaskSetter struct {
	ID          omit.Val[string]    `db:"id,pk" `
	Title       omit.Val[string]    `db:"title" `
	IsCompleted omit.Val[bool]      `db:"is_completed" `
	CreatedAt   omit.Val[time.Time] `db:"created_at" `
}

func (s TaskSetter) SetColumns() []string {
	vals := make([]string, 0, 4)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Title.IsValue() {
		vals = append(vals, "title")
	}
	if s.IsCompleted.IsValue() {
		vals = append(vals, "is_completed")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	return vals
}

func (s TaskSetter) Overwrite(t *Task) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Title.IsValue() {
		t.Title = s.Title.MustGet()
	}
	if s.IsCompleted.IsValue() {
		t.IsCompleted = s.IsCompleted.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
}

func (s *TaskSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Tasks.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 4)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Title.IsValue() {
			vals[1] = psql.Arg(s.Title.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.IsCompleted.IsValue() {
			vals[2] = psql.Arg(s.IsCompleted.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[3] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s TaskSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s TaskSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 4)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Title.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "title")...),
			psql.Arg(s.Title),
		}})
	}

	if s.IsCompleted.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_completed")...),
			psql.Arg(s.IsCompleted),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	return exprs
}

// FindTask retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindTask(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*Task, error) {
	if len(cols) == 0 {
		return Tasks.Query(
			sm.Where(Tasks.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Tasks.Query(
		sm.Where(Tasks.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Tasks.Columns.Only(cols...)),
	).One(ctx, exec)
}

// TaskExists checks the presence of a single record by primary key
func TaskExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return Tasks.Query(
		sm.Where(Tasks.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Task is retrieved from the database
func (o *Task) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Tasks.AfterSelectHooks.RunHooks(ctx, exec, TaskSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Tasks.AfterInsertHooks.RunHooks(ctx, exec, TaskSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Tasks.AfterUpdateHooks.RunHooks(ctx, exec, TaskSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Tasks.AfterDeleteHooks.RunHooks(ctx, exec, TaskSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Task
func (o *Task) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Task) pkEQ() dialect.Expression {
	return psql.Quote("tasks", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Task
func (o *Task) Update(ctx context.Context, exec bob.Executor, s *TaskSetter) error {
	v, err := Tasks.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single Task record with an executor
func (o *Task) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Tasks.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Task using the executor
func (o *Task) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Tasks.Query(
		sm.Where(Tasks.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after TaskSlice is retrieved from the database
func (o TaskSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Tasks.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Tasks.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Tasks.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Tasks.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o TaskSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("tasks", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o TaskSlice) copyMatchingRows(from ...*Task) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o TaskSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Tasks.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Task:
				o.copyMatchingRows(retrieved)
			case []*Task:
				o.copyMatchingRows(retrieved...)
			case TaskSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Task or a slice of Task
				// then run the AfterUpdateHooks on the slice
				_, err = Tasks.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o TaskSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Tasks.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Task:
				o.copyMatchingRows(retrieved)
			case []*Task:
				o.copyMatchingRows(retrieved...)
			case TaskSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Task or a slice of Task
				// then run the AfterDeleteHooks on the slice
				_, err = Tasks.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o TaskSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals TaskSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Tasks.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o TaskSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Tasks.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o TaskSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Tasks.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type taskWhere[Q psql.Filterable] struct {
	ID          psql.WhereMod[Q, string]
	Title       psql.WhereMod[Q, string]
	IsCompleted psql.WhereMod[Q, bool]
	CreatedAt   psql.WhereMod[Q, time.Time]
}

func (taskWhere[Q]) AliasedAs(alias string) taskWhere[Q] {
	return buildTaskWhere[Q](buildTaskColumns(alias))
}

func buildTaskWhere[Q psql.Filterable](cols taskColumns) taskWhere[Q] {
	return taskWhere[Q]{
		ID:          psql.Where[Q, string](cols.ID),
		Title:       psql.Where[Q, string](cols.Title),
		IsCompleted: psql.Where[Q, bool](cols.IsCompleted),
		CreatedAt:   psql.Where[Q, time.Time](cols.CreatedAt),
	}
}
