# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: local
      POSTGRES_DB: local
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
