// Code generated by BobGen sql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "github.com/stephenafamo/bob"

// Set the testDB to enable tests that use the database
var testDB bob.Transactor[bob.Tx]

// Make sure the type List runs hooks after queries
var _ bob.HookableType = &List{}

// Make sure the type Task runs hooks after queries
var _ bob.HookableType = &Task{}
