bases:
- ../../../infra/kustomize/shared/deployment

namePrefix: hello-world-

images:
- name: image
  newName: ghcr.io/brunoluiz/go-lab/hello-world
  newTag: latest

patches:
- path: config.json
  target:
    group: apps
    version: v1
    kind: Deployment
    name: app
