// Code generated by BobGen sql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var ListErrors = &listErrors{
	ErrUniqueListsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "lists",
		columns: []string{"id"},
		s:       "lists_pkey",
	},
}

type listErrors struct {
	ErrUniqueListsPkey *UniqueConstraintError
}
