// Code generated by BobGen sql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var TaskErrors = &taskErrors{
	ErrUniqueTasksPkey: &UniqueConstraintError{
		schema:  "",
		table:   "tasks",
		columns: []string{"id"},
		s:       "tasks_pkey",
	},
}

type taskErrors struct {
	ErrUniqueTasksPkey *UniqueConstraintError
}
