name: Cache Go Modules
description: Cache Go modules to speed up builds
runs:
  using: composite
  steps:
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
