openapi: 3.0.3
info:
  title: Tech Radar
  description: Tech radar management
  contact:
    email: contact@brunoluiz.net
  version: 1.0.0
paths:
  /api/v1/radars:
    post:
      tags: [radars]
      operationId: addRadar
      requestBody:
        $ref: './components/requestBodies/RadarAddRequest.yaml'
      responses:
        '201':
          $ref: './components/responses/RadarAddResponse.yaml'
        '400':
          $ref: './components/responses/CoreBadRequest.yaml'
  /api/v1/radars/{radar_id}:
    get:
      tags: [radar]
      operationId: getRadarById
      parameters:
        - name: radar_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: './components/responses/RadarGetByIDResponse.yaml'
        '400':
          $ref: './components/responses/CoreBadRequest.yaml'
        '404':
          $ref: './components/responses/CoreNotFound.yaml'
    delete:
      tags: [radar]
      operationId: deleteRadar
      parameters:
        - name: radar_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: './components/responses/CoreSuccess.yaml'
        '404':
          $ref: './components/responses/CoreNotFound.yaml'
    put:
      tags: [radar]
      operationId: updateRadar
      parameters:
        - name: radar_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        $ref: './components/requestBodies/RadarUpdateRequest.yaml'
      responses:
        '200':
          $ref: './components/responses/RadarUpdateResponse.yaml'
        '400':
          $ref: './components/responses/CoreBadRequest.yaml'
        '404':
          $ref: './components/responses/CoreNotFound.yaml'
  /api/v1/radars/{radar_id}/items:
    get:
      tags: [radars]
      operationId: getRadarItems
      parameters:
        - name: radar_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: './components/responses/RadarItemGetByIDResponse.yaml'
        '400':
          $ref: './components/responses/CoreBadRequest.yaml'
    post:
      tags: [radars]
      operationId: addRadarItem
      parameters:
        - name: radar_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        $ref: './components/requestBodies/RadarItemAddRequest.yaml'
      responses:
        '201':
          $ref: './components/responses/RadarItemAddResponse.yaml'
        '400':
          $ref: './components/responses/CoreBadRequest.yaml'
  /api/v1/radars/{radar_id}/items/{radar_item_id}:
    put:
      tags: [radar]
      operationId: updateRadarItem
      parameters:
        - name: radar_id
          in: path
          required: true
          schema:
            type: string
        - name: radar_item_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        $ref: './components/requestBodies/RadarItemUpdateRequest.yaml'
      responses:
        '200':
          $ref: './components/responses/RadarItemUpdateResponse.yaml'
        '400':
          $ref: './components/responses/CoreBadRequest.yaml'
        '404':
          $ref: './components/responses/CoreNotFound.yaml'
components:
  schemas:
    Radar:
      required:
        - id
        - title
        - created_at
        - updated_at
        - quadrants
        - items
      type: object
      properties:
        id:
          type: string
          example: 0ujsswThIGTUYm2K8FjOOfXtY1K
        title:
          type: string
          example: My radar
        items:
          type: array
          items:
            $ref: '#/components/schemas/RadarItem'
        quadrants:
          type: array
          items:
            $ref: '#/components/schemas/RadarQuadrant'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    RadarItem:
      required:
        - id
        - name
        - description
        - quadrant
        - created_at
        - updated_at
      type: object
      properties:
        id:
          type: string
          example: 0ujsswThIGTUYm2K8FjOOfXtY1K
        name:
          type: string
        description:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        quadrant:
          $ref: '#/components/schemas/RadarQuadrant'
    RadarQuadrant:
      required:
        - name
        - id
      type: object
      properties:
        id:
          type: string
          example: 0ujsswThIGTUYm2K8FjOOfXtY1K
        name:
          type: string
