apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "deployment.name" . }}
  labels:
    {{- include "deployment.labels.standard" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "deployment.labels.matchLabels" . | nindent 6 }}
