{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployment.name" . }}
  labels:
    {{- include "deployment.labels.standard" . | nindent 4 }}
spec:
  ports: {{- range .Values.deployment.ports }}
    - protocol: TCP
      port: {{ . }}
      targetPort: {{ . }}
  {{- end }}
  selector:
    {{- include "deployment.labels.matchLabels" . | nindent 4 }}
{{- end }}
