{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "deployment.name" }}
  labels:
    {{- include "deployment.labels.standard" | nindent 4 }}
  annotations:
    {{- include "deployment.serviceAccount.annotations" | nindent 4 }}
{{- end }}
