apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app.kubernetes.io/name: app
spec:
  selector:
    app.kubernetes.io/name: app
  ports:
    - protocol: HTTP
      port: 3000
      targetPort: 3000
    - protocol: TCP
      port: 4000
      targetPort: 400
