name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.build.outputs.config }}
    steps:
      - uses: actions/checkout@v4
      - id: build
        run: |
          config=$(cat .ko.yaml | yq -o json | jq -c)
          echo "config=$config" >> $GITHUB_OUTPUT

  build:
    name: Build (${{ matrix.config.id }})
    runs-on: ubuntu-latest
    needs: [prepare]
    strategy:
      matrix:
        config: ${{ fromJSON(needs.prepare.outputs.build).builds }}
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: ko-build/setup-ko@v0.6
      - run: |
          export KO_DOCKER_REPO=ghcr.io/${{ matrix.config.id }}
          # needs package read/write/delete + repo
          echo ${{ secrets.GITHUB_TOKEN }} | ko login ghcr.io -u brunoluiz --password-stdin
          ko build ${{ matrix.config.main }} --bare
