name: Build (Go)

on:
  workflow_call:
    inputs:
      id:
        type: string
        required: true
      main:
        type: string
        required: true
      helm:
        type: string
    outputs:
      id:
        value: ${{ inputs.id }}
      helm:
        value: ${{ inputs.helm }}
      image:
        value: ${{ jobs.build.outputs.image }}

jobs:
  build:
    name: Build (${{ inputs.id }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      id: ${{ inputs.id }}
      helm: ${{ inputs.helm }}
      image: ${{ steps.ko.outputs.image }}
    permissions:
      contents: write # required for trivy
      security-events: write # required for trivy
      packages: write # required for docker
      attestations: write
      id-token: write # required for cosign??
    steps:
      - uses: actions/checkout@v4
      - uses: brunoluiz/go-lab/.github/actions/build-go@main
        id: ko
        with:
          id: ${{ inputs.id }}
          helm: ${{ inputs.helm }}
          main: ${{ inputs.main }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
