name: Release

on:
  workflow_call:
    inputs:
      id:
        type: string
        required: true
      main:
        type: string
        required: true
      helm:
        type: string

jobs:
  build:
    name: Build (${{ inputs.id }})
    uses: ./.github/workflows/go-build.yaml
    with:
      id: ${{ inputs.id }}
      helm: ${{ inputs.helm }}
      main: ${{ inputs.main }}
    permissions:
      contents: write # required for trivy
      security-events: write # required for trivy
      packages: write # required for docker
      attestations: write
      id-token: write # required for cosign??

  # deploy:
  #   name: Deploy (${{ matrix.config.id }})
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   needs: [build]
  #   permissions:
  #     contents: write # required for trivy
  #     security-events: write # required for trivy
  #     packages: write # required for docker
  #     attestations: write
  #     id-token: write # required for cosign??
  #   strategy:
  #     matrix:
  #       config: {{ fromJSON(needs.build.outputs) }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: |-
  #         sh .github/scripts/deploy-digest.sh ${{ matrix.config.image }} ${{ matrix.config.helm }}
  #     - uses: stefanzweifel/git-auto-commit-action@v5
  #       with:
  #         commit_message: "ci: deploy {{ matrix.config.image }}"

